name = "Hindi"
version = "0.1.1"

# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Hindi spellchecker"
hi = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Hindi, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
hi = "TRANSLATE: A spellchecker for Hindi, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.hi"

[windows]
system_product_code = "{464ECF2A-89C0-41E6-8C36-E22713FC1031}_is1"
legacy_product_codes = [
    { value = "DBC2B2CC-628D-4C57-9DA7-B8817F51FD6C", kind = "nsis" },
    { value = "7259185E-4A50-45AC-8EE8-4AB4FAE63F8A", kind = "nsis" }
]
