template = "https://github.com/giellalt/template-lang-und"
rev_id = 317
template_sha = "3d0bcfa8020a96bc946192565f7e92213470a110"

[replacements]
__GLOTTOLOG_ID__ = "hind1269"
__REPO__ = "lang-hin"
__UND2C__ = "hi"
__UNDEFINED__ = "Hindi"
__UND__ = "hin"
