template = "https://github.com/giellalt/template-lang-und"
rev_id = 289
template_sha = "599009dae90448ef6fe32b71f7a6880293f3d546"

[replacements]
__GLOTTOLOG_ID__ = "hind1269"
__REPO__ = "lang-hin"
__UND2C__ = "hi"
__UNDEFINED__ = "Hindi"
__UND__ = "hin"
